services:
  billing_parser:
    build:
      context: .
      dockerfile: Dockerfile
    image: baiks384/billing-parser
    container_name: billing_parser
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_SERVER_PORT: 8084
      SPRING_SERVER_ADDRESS: 0.0.0.0
    networks:
      - ednetwork

networks:
  ednetwork:
    driver: bridge
